'use server';

/**
 * Generate README.md and setup guide for a generated project.
 *
 * Two separate model calls so markdown in the README never breaks JSON parsing:
 *  1. Commands-only call: returns a plain JSON array of strings — trivial to parse.
 *  2. README call: returns raw markdown prose — no JSON involved.
 */

import { litellmChatCompletion } from '@/ai/litellm-client';
import { getModelForTask } from './model-router';
import type { ProjectPlan, GeneratedFile } from './types';

export interface ReadmeResult {
  readmeContent: string;
  setupCommands: string[];
}

/** Step 1: ask only for the ordered list of terminal commands as a JSON array. */
async function fetchSetupCommands(
  plan: ProjectPlan,
  model: string
): Promise<string[]> {
  const arch = plan.architecture;
  const prompt = `Project type: ${arch.projectType}
Frameworks: ${arch.frameworks.join(', ') || 'none'}
Dependencies: ${arch.dependencies.join(', ') || 'none'}

Output ONLY a JSON array of strings: the exact terminal commands a beginner must run in order to install dependencies and start this project (e.g. ["npm init -y", "npm install react react-dom", "npm start"]).
No explanations. No extra keys. Only the JSON array.`;

  const raw = await litellmChatCompletion({
    messages: [
      { role: 'system', content: 'You output only valid JSON arrays of terminal command strings. No prose.' },
      { role: 'user', content: prompt },
    ],
    model,
    maxTokens: 256,
    temperature: 0.1,
  });

  const cleaned = raw.trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/, '');
  try {
    const parsed = JSON.parse(cleaned);
    if (Array.isArray(parsed)) {
      return parsed.filter((c): c is string => typeof c === 'string' && c.trim().length > 0);
    }
  } catch {
    // try extracting array substring
    const match = cleaned.match(/\[[\s\S]*\]/);
    if (match) {
      try {
        const arr = JSON.parse(match[0]);
        if (Array.isArray(arr)) {
          return arr.filter((c): c is string => typeof c === 'string' && c.trim().length > 0);
        }
      } catch { /* fall through */ }
    }
  }
  return [];
}

/** Step 2: generate the README as plain markdown (no JSON wrapping). */
async function fetchReadmeMarkdown(
  plan: ProjectPlan,
  files: GeneratedFile[],
  directoryTree: string,
  setupCommands: string[],
  model: string
): Promise<string> {
  const arch = plan.architecture;
  const fileList = files.map((f) => `- ${f.path}`).join('\n');
  const commandsBlock =
    setupCommands.length > 0
      ? setupCommands.map((c, i) => `${i + 1}. \`${c}\``).join('\n')
      : '(run the appropriate package manager install and start commands)';

  const systemPrompt = `You are Code M. Write a concise README.md for a beginner who will:
1. Create a project folder.
2. Recreate the directory structure shown below.
3. Copy each generated file into its correct path (imports are already correct).
4. Run the listed commands.

Project type: ${arch.projectType}
Frameworks: ${arch.frameworks.join(', ') || 'N/A'}
Dependencies: ${arch.dependencies.join(', ') || 'N/A'}

Directory structure:
\`\`\`
${directoryTree}
\`\`\`

Files:
${fileList}

Commands to run (already determined):
${commandsBlock}

Output ONLY the raw README.md content. Do NOT wrap it in a code fence. Keep it under 120 lines.`;

  const content = await litellmChatCompletion({
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: 'Write the README.md.' },
    ],
    model,
    maxTokens: 1024,
    temperature: 0.3,
  });

  const trimmed = content.trim().replace(/^```markdown\s*/i, '').replace(/^```\s*/, '').replace(/\s*```\s*$/, '');
  return trimmed || `# Project\n\nGenerated by Code M.\n\n## Directory structure\n\n\`\`\`\n${directoryTree}\n\`\`\`\n\n## Commands\n\n${commandsBlock}`;
}

export async function generateReadme(
  plan: ProjectPlan,
  files: GeneratedFile[],
  directoryTree: string
): Promise<ReadmeResult> {
  const model = getModelForTask('code_generation');

  // Run both calls — commands first (fast, tiny output) then README uses the result
  const setupCommands = await fetchSetupCommands(plan, model);
  const readmeContent = await fetchReadmeMarkdown(plan, files, directoryTree, setupCommands, model);

  return { readmeContent, setupCommands };
}
