// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for generating emotional prompts to guide conversations.
 *
 * - generateEmotionalPrompt - A function that generates an emotional prompt.
 * - GenerateEmotionalPromptInput - The input type for the generateEmotionalPrompt function.
 * - GenerateEmotionalPromptOutput - The output type for the generateEmotionalPrompt function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateEmotionalPromptInputSchema = z.object({
  emotion: z.string().describe('The emotion to base the prompt on.'),
  topic: z.string().describe('The topic of the conversation.'),
});
export type GenerateEmotionalPromptInput = z.infer<typeof GenerateEmotionalPromptInputSchema>;

const GenerateEmotionalPromptOutputSchema = z.object({
  prompt: z.string().describe('The generated emotional prompt.'),
});
export type GenerateEmotionalPromptOutput = z.infer<typeof GenerateEmotionalPromptOutputSchema>;

export async function generateEmotionalPrompt(input: GenerateEmotionalPromptInput): Promise<GenerateEmotionalPromptOutput> {
  return generateEmotionalPromptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateEmotionalPromptPrompt',
  input: {schema: GenerateEmotionalPromptInputSchema},
  output: {schema: GenerateEmotionalPromptOutputSchema},
  prompt: `You are an AI assistant designed to generate emotional prompts for conversations.
  Based on the emotion: {{{emotion}}} and topic: {{{topic}}}, create a prompt to start a conversation.`,
});

const generateEmotionalPromptFlow = ai.defineFlow(
  {
    name: 'generateEmotionalPromptFlow',
    inputSchema: GenerateEmotionalPromptInputSchema,
    outputSchema: GenerateEmotionalPromptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
