// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a flow for generating emotional prompts to guide conversations.
 *
 * - generateEmotionalPrompt - A function that generates an emotional prompt.
 * - GenerateEmotionalPromptInput - The input type for the generateEmotionalPrompt function.
 * - GenerateEmotionalPromptOutput - The return type for the generateEmotionalPrompt function.
 *
 * Uses LiteLLM for chat instead of Genkit/Gemini.
 */

import { z } from 'zod';
import { litellmChatCompletion } from '@/ai/litellm-client';

const GenerateEmotionalPromptInputSchema = z.object({
  emotion: z.string().describe('The emotion to base the prompt on.'),
  topic: z.string().describe('The topic of the conversation.'),
});
export type GenerateEmotionalPromptInput = z.infer<
  typeof GenerateEmotionalPromptInputSchema
>;

const GenerateEmotionalPromptOutputSchema = z.object({
  prompt: z.string().describe('The generated emotional prompt.'),
});
export type GenerateEmotionalPromptOutput = z.infer<
  typeof GenerateEmotionalPromptOutputSchema
>;

const PROMPT_TEMPLATE = `You are an AI assistant designed to generate emotional prompts for conversations.
Based on the emotion: {{emotion}} and topic: {{topic}}, create a prompt to start a conversation.`;

export async function generateEmotionalPrompt(
  input: GenerateEmotionalPromptInput
): Promise<GenerateEmotionalPromptOutput> {
  const userMessage = PROMPT_TEMPLATE.replace('{{emotion}}', input.emotion).replace(
    '{{topic}}',
    input.topic
  );

  const content = await litellmChatCompletion({
    messages: [{ role: 'user', content: userMessage }],
    maxTokens: 256,
    temperature: 0.7,
  });

  return { prompt: content.trim() };
}
